### ISSUE TITLE
Clicking a division in the structure tree should show the first media object in it in the media view

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#5479] opened 2022-12-07 14:54 UTC
Clicking on a media object in the structure tree will show it in the media view. On the opposite, if you click on a division, the media view doesn’t change.

**Goal:** The user expectation here would be for the same to happen, i.e. the media view switches to the first piece of media associated with the division clicked.

**Comment by IkramMaalej** [comment] 2022-12-08 09:03
Duplicate of #4977

**Closed** 2022-12-12 13:10 UTC
Labels: duplicate
