### ISSUE TITLE
Expand/collapse arrow in process list visible for non-hierarchic processes

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#5296] opened 2022-08-18 06:28 UTC
**Describe the bug**
The blue expand/collapse arrow in the process list (next to the checkbox) is visible in each row, even for non-hierarchical processes.

**To Reproduce**
1. See process list

**Expected behavior**
The arrow shouldn’t be there for non-hierarchical processes

**Release**
3.4.3

**Comment by solth** [comment] 2022-08-29 08:16
I have never encountered this particular problem, and it does not seem to occur in the current master. Can you confirm that it is fixed in the current code?

**Comment by andre-hohmann** [comment] 2022-08-29 08:50
In 3.4.4-SNAPSHOT it occurs, too - if this is the behavior, which @matthias-ronge described

![exmple](https://user-images.githubusercontent.com/14835770/187162399-2678832f-8b98-4c71-ae9c-cf702210f623.jpg)

**Comment by matthias-ronge** [comment] 2022-08-29 08:51
This is what I mean

**Comment by solth** [comment] 2022-08-29 09:18
This is not a bug. The row expansion for processes contains other information apart from data about process hierarchies. For example, it contains a button to self-assign the current task of a process, if applicable:
<img width="368" alt="Bildschirmfoto 2022-08-29 um 11 16 42" src="https://user-images.githubusercontent.com/19183925/187168250-e5456d4e-6d23-4ea5-9a7e-e6a7273f25a0.png">


So the row expansion has a meaning for all processes, even those that aren't part of a process hierarchy. Information about whether parent or child processes exist is shown in the adjacent column like this:
<img width="164" alt="Bildschirmfoto 2022-08-29 um 11 09 39" src="https://user-images.githubusercontent.com/19183925/187167773-015617d2-802b-417a-ac88-dd99045ea12a.png">

**Comment by matthias-ronge** [comment] 2022-08-29 09:31
Okay, the reason has changed. In the past, the expansion was specifically for hierarchy. Needs better communication …

But why there is no downward expansion in you screenshot for case 241? Is it complete? If the downward expansion is more general, it should be there all the time.

And, maybe more (a lot of the) icons of the “actions“ column then could go into the expansion … …

**Comment by solth** [comment] 2022-08-29 09:35
> Okay, the reason has changed. In the past, the expansion was specifically for hierarchy. Needs better communication …
> 
That's true for many parts of Kitodo.

> But why there is no downward expansion in you screenshot for case 241? Is it complete? If the downward expansion is more general, it should be there all the time.

This is a screenshot from my development system where I test many different kinds of processes. The process with ID 241 is not part of a hierarchy, that's the reason it has no "hierarchy markers".

> 
> And, maybe more (a lot of the) icons of the “actions“ column then could go into the expansion … …

True again, but that's a different story again and not a bug.

I will close this issue as the reported behavior is working as intended.

**Closed by solth** 2022-08-29 09:35 UTC
Labels: bug

**Comment by matthias-ronge** [comment] 2022-08-29 10:09
> The process with ID 241 is not part of a hierarchy, that's the reason it has no "hierarchy markers".

True, but, as it may have an open task, it should have an expansion to take over that task, shouldn’t it?

**Comment by solth** [comment] 2022-08-29 10:19
The row toggler is not displayed if no hierarchy _and_ no current task for the current user is available:
```<p:rowToggler rendered="#{process.getParentID() ne 0 or process.hasChildren() or ProcessForm.getCurrentTasksForUser(process).size() gt 0}"/>```
