### ISSUE TITLE
Detail view in the metadata editor is strange, when browser zoom is reduced

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#4711] opened 2021-09-30 08:19 UTC
### Problem
In the Chrome browser, the detail view in the metadata editor "gets lost" when the browser zoom is reduced beneath 100%. It is necessary to scroll to find the image. See the GIF in Examples.

### Solution
The detail view should be visible in all zoom-levels of the browser. 

### Examples
![DetailansichtVerschoben](https://user-images.githubusercontent.com/14835770/135414893-e9a2c24d-06a5-4c91-9563-637cc64c775e.gif)

**Comment by solth** [comment] 2021-09-30 10:35
Duplicate of #4661

**Closed** 2021-09-30 10:38 UTC
Labels: bug, 3.x
