### ISSUE TITLE
Last image not visible in structure tree

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4951] opened 2022-01-31 13:24 UTC
It is a general problem that the last image is not visible in the structure tree:

![Last image cannot be accessed](https://user-images.githubusercontent.com/3040657/151801353-24bf2b85-4d25-417f-967f-db499c749451.png)

Also, the „knob“ of the scroll bar is hidden behind the comment box

**Goal:** The last image should be visible when you scroll all down.

**Comment by andre-hohmann** [comment] 2022-08-15 05:32
In "KITODO.PRODUCTION Version 3.4.4-SNAPSHOT", this seems to be solved. 
Can anyone confirm this?

**Comment by oliver-stoehr** [comment] 2022-10-10 11:17
I can confirm, this bug was fixed by #5203.

**Closed by oliver-stoehr** 2022-10-10 11:17 UTC
Labels: bug
