### ISSUE TITLE
VariableReplacer does not work properly in the script step

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3718] opened 2020-06-03 06:51 UTC
Reported by @stefanCCS 
> I have tried out the following as "Script Path":
> /home/workshop/myScripts/mySimpleScript.sh (processpath)
> I would have expected to find in my Script as command line parameter the "process path".
> Unfortunately, I have not found anything (no command line parameter at all

**Comment by stefanCCS** [comment] 2020-06-19 12:54
In  version 3.2 build 09.06.2020 I can confirm that at least the parameter 
(processid) (processtitle) (metaFile)
are given to the script als command line parameter.
Others (ocrbasispath) (ocrplaintextpath) have NOT given any value to the script.
More parameter I have tried out so far.

**Comment by stefanCCS** [comment] 2020-06-29 11:08
Finally, I have checked all variables available in [VariableReplacer](https://github.com/kitodo/kitodo-production/blob/master/Kitodo/src/main/java/org/kitodo/production/helper/VariableReplacer.java) as follows:
Putting a script task in a workflow with the following parameters:
`myScript.sh "1:(tifurl)" "2: (tifpath)" "3:(origurl)" "4:(origpath)" "5: (imageurl)" "6:(imagepath)" "7:(processpath)" "8:(importpath)" "9:(sourcepath)" "10:(ocrbasispath)" "11:(ocrplaintextpath)" "12:(metaFile)" "13:(prefs)" "14:(processtitle)" "15:(processid)" "16: (stepid)" "17: (stepname)" 
`

Result is:
`
"1:file://202006291236_media"
"2:
202006291236_media"
"3:file://master_202006291236_media"
"4:master_202006291236_media"
"5:
file://"
"6:"
"7:"
"8:"
"9:"
"10:"
"11:"
"12:meta"
"13:/usr/local/kitodo/rulesets/ruleset_CCS_min.xml"
"14:202006291236"
"15:24"
"16:164"
"17:printAllPossibleParameters"
`
--> with this you can identify, which paratemer creates which value, and evaluate, if this is correct or not (I personally cannot do this evaluation, as I do not know, what is intended).

**Comment by matthias-ronge** [comment] 2020-08-05 12:41
Thanks for the work! I see I misunderstood the ticket. The placeholders are not passed to the script, the placeholders are replaced, but the value to be used has not been determined, therefore an empty string is put in place.  
The `file://` URIs with relative paths are nonsensical.

**Comment by matthias-ronge** [comment] 2020-10-29 11:10
I think the correct answer here is that only the following variables should be used. These also work and, in my opinion, are sufficient.

```
variable name  | example value
---------------+-----------------------------------------------
(processid)    | 24
(processtitle) | 202006291236
(stepid)       | 164
(stepname)     | printAllPossibleParameters
(prefs)        | /usr/local/kitodo/rulesets/ruleset_CCS_min.xml
```

The others are relics from Production 2.x and should be removed in 3.x. Here are samples what can be used instead of the other options:

```
legacy name        | possible replacement
-------------------+------------------------------------------------------------------------------
(tifurl)           | http://kitodo.example.org/content/(processid)/images/(processtitle)_tif/
(tifpath)          | /mnt/data/metadata/(processid)/images/(processtitle)_tif/
(origurl)          | http://kitodo.example.org/content/(processid)/images/orig_(processtitle)_tif/
(origpath)         | /mnt/data/metadata/(processid)/images/orig_(processtitle)_tif/
(imageurl)         | http://kitodo.example.org/content/(processid)/jpgs/max/
(imagepath)        | /mnt/data/metadata/(processid)/jpgs/max/
(processpath)      | /mnt/data/metadata/(processid)/
(importpath)       | /mnt/data/metadata/(processid)/import/
(sourcepath)       | /mnt/data/metadata/(processid)/images/source_(processtitle)_tif/
(ocrbasispath)     | /mnt/data/metadata/(processid)/images/(processtitle)_tif/
(ocrplaintextpath) | /mnt/data/metadata/(processid)/ocr/alto
(metaFile)         | /mnt/data/metadata/(processid)/meta.xml
```

As you see, those values depend on your local setup and shouldn’t even be hard-coded in the application.

**Comment by stefanCCS** [comment] 2020-10-29 11:23
very reasonable, many thanks for you answer.

**Comment by henning-gerhardt** [comment] 2020-10-29 11:39
In my opinion remove of path variables are wrong and should stay.

**Comment by Kathrin-Huber** [comment] 2020-10-30 09:22
I agree, that we should keep those variables, because for example `imagepath` can be configured in the project und should therefore not be hardcoded.

**Comment by matthias-ronge** [comment] 2020-10-30 11:21
If the goal is that configured scripts from version 2 should continue to work in version 3, these values **must deliver exactly the same results** as in version 2. They must look like this if `useOrigFolder` is `true`:

```
(processpath)      | ConfigCore.getParameter(ParameterCore.DIR_PROCESSES).replace('\\', '/') + process.getId() +'/'
                   |
(imagepath)        | processPath + "images/"
(imageurl)         | "file:/" + processPath + "images/"
(importpath)       | processPath + "import/"
(metaFile)         | processPath + "meta.xml"
(ocrbasispath)     | processPath + "ocr/"
(ocrplaintextpath) | processPath + "ocr/" + process.getTitle() + "_txt/"
(origpath)         | processPath + "images/" + ConfigCore.getParameter(ParameterCore.DIRECTORY_PREFIX) + '_'
                   |     + process.getTitle() + '_' + ConfigCore.getParameter(ParameterCore.DIRECTORY_SUFFIX) + '/'
(origurl)          | "file:/" + processPath + "images/" + ConfigCore.getParameter(ParameterCore.DIRECTORY_PREFIX)
                   |     + '_' + process.getTitle() + '_' + ConfigCore.getParameter(ParameterCore.DIRECTORY_SUFFIX)
                   |     + '/'
(sourcepath)       | processPath + "images/" + process.getTitle() + "_source"
(tifpath)          | processPath + "images/" + process.getTitle() + '_' +
                   |     ConfigCore.getParameter(ParameterCore.DIRECTORY_SUFFIX) + '/'
(tifurl)           | "file:/" + processPath + "images/" + process.getTitle() + '_'
                   |     + ConfigCore.getParameter(ParameterCore.DIRECTORY_SUFFIX) + '/'
```

With `useOrigFolder=false`, `(origpath)` and `(origurl)` take the same values as `(tifpath)` or `(tifurl)`, respectively.

**Consequences:** There will be a notably set of hard-coded path strings that do not necessarily correspond to any folder settings. They will be a potential source of confusion in the future. The configuration settings `DIRECTORY_PREFIX`, `DIRECTORY_SUFFIX` and `useOrigFolder` cannot removed from configuration. Their meaning needs to be properly documented.

**Comment by matthias-ronge** [comment] 2020-10-30 14:28
Wouldn't it make more sense to convert these during the migration? Production 3.x is flexible in terms of folder design and we should avoid dragging along old baggage.

The fact that the database field is too short for the script string should be fixed. By the way, for me it is only 255 characters (in 2.x)!

**Comment by stefanCCS** [comment] 2020-11-03 10:51
Please let me share my view on this:
In my opinion it has to be differentiated between:
- Kitodo V3 function.
- V2->V3 migration topics.

**Just looking at pure V3 function first:**
Here, I would expect, that I can get via variables all data, which are dependent of current Project/Process/Task.
On the other hand, it is not needed, that I get information about Kitodo-SW-Environment, as these are fixed in my system, and I know this (e.g. in my script, which is called from Kitodo).
In detail this means, I need the information @matthias-ronge  has already mentioned above:
- (processid)
- (processtitle)
- (stepid) 
- (stepname)
- (prefs)

Additionally, I need the information about the folders, which I can configure in the Project, which are (at least, maybe more folders can be created):
- (imagepath)
- (origpath)
- (ocrplaintextpath)
- (thumbspath)  - _which is not existing at this moment_

**For V2->V3 topics, I agree to @matthias-ronge  proposal:**
All V2 variables, which are not supported anymore, need to be transferred to the new variables in the migration project.

**Comment by matthias-ronge** [comment] 2020-11-03 11:01
The problem is that (imagepath), (origpath), and (ocrplaintextpath) **point to hard-coded path values** and are unrelated to folder settings. They won’t match your folder settings, except by accident. Therefore I would have wanted it to be removed in version 3.

**Comment by stefanCCS** [comment] 2020-11-03 11:06
Oh, good to know.

In my opinion this would mean, to add new variables and remove the old ones (or change the meaning of the existing ones), just to have a chance of getting dynamically outside Kitodo-SW these folder names for some scripting pupose.

**Closed** 2021-06-24 15:19 UTC
Labels: 3.x, bug, documentation
