### ISSUE TITLE
Not all files are assigned to superordinate structure elements

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#5873] opened 2024-01-10 10:07 UTC
**Describe the bug**
If in the metadata editor a structure element is created and the first file(s) is/are assigned to it, this/these file(s) are not referenced any more to the superordinate structure element. See examples in section _Additional context_. 

It seems that during the export, the references are created correctly. 

Is this is an deception, because not all files are shown in the assigned structure elements?
Are internally only the files assigned to a structure element, which are directly referenced to it (without any intermediate structure element)?

**To Reproduce**
1. Open a process with files
2. Create a structure element and assign the first file(s)
3. Check the assigned files to the structural elements: [Zeige zugewiesene Seiten](https://github.com/kitodo/kitodo-production/wiki/Anpassungen-der-Anzeige-im-Strukturbaum#zeige-zugewiesene-seiten)
4. Assign more file(s) to the created structural element
5. Check the assigned files of all structural elements

**Expected behavior**
The structure element should "contain" references to all subordinated media files and structure elements

**Release**
3.6.1

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Additional context**

Examples 

- Example 1
  - Handschrift[1 : - | 20 : - ] `(This is correct)`
    - 1 : -
    - 2 : -
    - 3 : -
    - 4 : -
    - ...

- Example 2
  - Handschrift[2 : - | 20 : - ] `(I would expect [1 : - | 20 : - ])`
    - Einband[1 : -]
      - 1 : -
    - 2 : -
    - 3 : -
    - 4 : -
    -   ...

- Example 3
  - Handschrift[3 : - | 20 : - ] `(I would expect [1 : - | 20 : - ])`
    - Einband[1 : - | 2 : -]
      - 1 : -
      - 2 : -
    - 3 : -
    - 4 : -
    - ...

- Example 4
  - Handschrift[5 : - | 20 : - ] `(I would expect [1 : - | 20 : - ])`
    - Einband[1 : - | 3 : -]
      - 1 : -
      - 2 : -
      - 3 : -
    - Titelblatt[4 : -]
      - 4 : -
      - 5 : -
    - ...
- Example 5
  - Handschrift[1 : - | 20 : - ] `(This is correct)`
    - 1 : -
    - Einband[2 : - | 3 : -]
      - 2 : -
    - 3 : -
    - Titelblatt[4 : -]
      - 4 : -
    - 5 : -

**Comment by matthias-ronge** [comment] 2024-01-10 11:17
Hi @andre-hohmann, 

This is intended behaviour. A `<File>` is always only assigned to the lowest structural element to which it belongs. The redundant information **is added during the export**. This is based on the fact that a file that is assigned in the suborders should also be assigned in the parent order in METS. That's why it's made that way during export. **In internal format**, this information is _not necessary_ (since it is implied) and is therefore _not stored._

This is an example of why it is confusing that the internal storage format is also saved converted to a METS. **It must be clear to everyone that the application does not work internally in METS and the internal data is only saved converted as METS** because this was requested for the OCR-D projet, but this is saving an internal format that works completely differently. But, this was wanted. The original plan was to save the internal format as an internal format, for example Linked Data/Turtle format, but that was rejected during the process of 3.x development project. This is how this hybrid did come up, which is just confusing for everyone.

I will close this issue, as it is not an error.

**Comment by andre-hohmann** [comment] 2024-01-10 11:20
@matthias-ronge : Thanks a lot for the background information! 
Now i can explain it better to my colleagues.

**Closed** 2024-01-10 11:20 UTC
Labels: bug, documentation, question, metadata editor
