### ISSUE TITLE
Remove position query when creating structure in existing structure

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3601] opened 2020-05-08 07:02 UTC
Example: You have assigned pages 14-37 to a _chapter_ structure. Now select pages 30-32 and select the _new structure element from selected pages_ function to make a _table_ (as a child of the chapter). The dialog gives a drop-down box _position_ with the options "as first sub-element of the current element", "as last sub-element of the current element", and "as parent element of the current element".

![Screenshot](https://user-images.githubusercontent.com/3040657/81380293-f091aa00-910a-11ea-9263-da93a412fc18.png)

**Goal:** The box is unnecessary and none of the options make sense. The position of the new child must be determined by the position of the pages within the chapter, i.e. pages 14-29 come before the table, then the table with pages 30-32, then pages 33-37.

**Comment by matthias-ronge** [comment] 2020-05-08 07:04
I gave the <kbd>question</kbd> badge because I don't know exactly what is going on with the options. If the selection is ignored, it would be an <kbd>improvement</kbd>, otherwise it would be a <kbd>bug</kbd> if it produced nonsense.

**Comment by solth** [comment] 2020-05-08 07:30
I think this is a duplicate of #3486

**Comment by andre-hohmann** [comment] 2020-05-11 15:18
The two options "as first sub-element of the current element" and "as last sub-element of the current element" do make sense from my point of view and they do work, Especially  when several structure elements already exist.

### Example: 
The following structure tree does exist: 

 Kapitel 1
  3 : 9
Monographie
 Kapitel 2
  4 : 25
  5 : 26
  6 : 29
  7 : 30
 Kapitel 3
  8 : 45
 Kapitel 4
  9 : 46
  10 : 47
  11 : 48
  12 : 49
  13 : 50
 Kapitel 5
  1 : 53
  2 : 54

When the following block of images is selected and "as first sub-element of the current element" is selected, it will be positioned before "Kapitel 1". If "as last sub-element of the current element" is selected, it will be positioned after "Kapitel 5". 

15 : 2
16 : 3
17 : 4
18 : 5
19 : 6
20 : 7

This approach is however similar to the procedure in the structure tree, where you can also select the beginning or the end of the structure elements. Of course, this could be realized by the insertion according to the  image numbers, too. Then, the user has no opportunity to influence the position of the new structure element. 

The option "as parent element of the current element" is from my point of view useless, too and could be removed. In my examples, it was never offered a structure type to me.

**Comment by matthias-ronge** [comment] 2020-11-03 11:04
Closely related to #3476 & #3486

**Closed** 2020-11-03 11:05 UTC
Labels: 3.x, duplicate
