### ISSUE TITLE
Exception, when creating hierarchical (2-layers) process

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#4811] opened 2021-11-08 15:37 UTC
Release 3.3.1
When trying to import and create a hierarchical process from the "child" PPN with automatic creation of the "parent" PPN process, an exception is created:
Import using this works fine (2 data sets are importet correctly).
![grafik](https://user-images.githubusercontent.com/61045115/140771247-28db921c-1eb6-4143-a048-5f4ace2281d4.png)
 But when trying the save this process the following exception is created:
![grafik](https://user-images.githubusercontent.com/61045115/140771372-cdb43470-97d7-4727-a824-23e377903289.png)
==> reproducable in production-demo.kitodo.org

==> in older release 3.3 this has worked correctly

**Comment by matthias-ronge** [comment] 2021-11-16 14:17
Duplicate of  #4591

**Closed** 2021-11-16 14:17 UTC
Labels: duplicate
