### ISSUE TITLE
Release 3.4.3: Missing Texts (in catalog loading interface)

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#5243] opened 2022-07-14 10:54 UTC
It looks like that from Release 3.4.2 to 3.4.3 some texts were added.
In the screenshot below you can see some missing texts
- basicData
- dataTransfer
==> please provide information what to do (as part of updating a system, most probably adding something in the message files)

![image](https://user-images.githubusercontent.com/61045115/178966832-1e76cb54-c680-4be7-801e-b774d8859d00.png)

**Comment by solth** [comment] 2022-07-14 12:06
Since the layout in that screenshot looks broken I think you just need to reload the page including the cache in your browser (similar perceived problems with broken page designs often occur after changes are made to the Kitodo.Production style sheets and are in fact nearly always just caused by old files cached by the browser). This might also resolve the supposed issue with the missing messages.

**Comment by stefanCCS** [comment] 2022-07-14 13:18
Well, this was a message-File issue.
(Not for the first time) I had to find the difference between the last two releases (which are a lot!) and merge this diff-result with my own customization.
I would appreciate very much, if with a new Release also changes in config files also would be provided.

**Comment by matthias-ronge** [comment] 2022-08-08 11:39
If you have the messages in a separate folder (like `/usr/local/kitodo/messages`) then you need to manually update the files in this folder. Typically it is better to delete this folder altogether, so the internal messages files are used which should be up-to-date.

**Comment by stefanCCS** [comment] 2022-08-08 14:32
Well, the installation documentation proposes to put the messages in a separate folder:
https://github.com/kitodo/kitodo-production/wiki/Installationsanleitung-f%C3%BCr-Kitodo.Production-3.4#9-programmordner-und--dateien-erstellen

But, anyway, my main concern is, that I always need to merge a new version of message files from a new release with my own customized message files (wherever they are located ...).
Therefore, my wish would be to get the information, what has changed in a message file with a new release.
( or deliver a "magic" script, which does this merging automatically ;-)   )

**Comment by stefanCCS** [comment] 2022-08-09 07:41
> I hold my changes of the message resource files into a git repository. The `main` branch contain the current files of the Kitodo.Poduction repository and the `custom` branch contain the custom changes. On a new release I put the message resources files from the Kitodo.Production release into the `main` branch as an update - so I can see, what is changed between the releases - and did a `git rebase` on the `custom` branch afterwards. If I get some merge conflicts on rebase then I know which lines I must adjust.

Nice idea - but still, I would appreciate VERY MUCH, if the changes would be put this release notes.

**Comment by henning-gerhardt** [comment] 2022-08-09 08:14
GIT can provide this changes as well and without blowing up the release notes:

`git dif <release-tag-one>...<release-tag-two> Kitodo/src/main/resources/messages/`

f.e.:

`git diff kitodo-production-3.4.2...kitodo-production-3.4.3 Kitodo/src/main/resources/messages/`

and this will you all changes into the resource message files.

**Comment by stefanCCS** [comment] 2022-08-09 08:44
Also, many thanks for this hint.
I think, this will only work, if you have checked-out everything locally (which I do not do, I only download the release files).
So, maybe this idea could be a starting point: If it is this easy to create this "diff", why not create this during build, and put this in a file, and link this file in the Release Notes?

**Comment by stefanCCS** [comment] 2022-11-24 13:14
@solth:
Please consider this as part of automatic Release generation (create the diff-files, as proposed by @henning-gerhardt put this somewhere on Github and reference this in the Release Notes).

**Comment by solth** [comment] 2024-06-06 10:06
Closing this issue since Kitodo 3.4 is not supported anymore.

@stefanCCS If you encounter the same problem in 3.6 or the current master, please open a new issue for it! Furthermore the changes between releases are now included in the release notes, as you can see for example here: https://github.com/kitodo/kitodo-production/releases/tag/kitodo-production-3.6.3

**Closed by solth** 2024-06-06 10:06 UTC
Labels: documentation, question
