### ISSUE TITLE
Release 3.5 - Exception when deleting a process

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#5450] opened 2022-11-23 10:11 UTC
I have created a process (with catalogue data, but I think, this does not matter).
After creation of this process, I deleted it.
Same thing is happening, if I delete the process after the process has already performed some tasks.
Then, I have got the following exception:
![image](https://user-images.githubusercontent.com/61045115/203520542-da28448e-c264-43bb-b71f-cac1d3048e58.png)
```
[ERROR] 2022-11-23 09:57:03.991 [http-nio-8080-exec-10] WebDav - errorUploading
java.io.IOException: No user for home directory!
        at org.kitodo.production.services.data.UserService.getHomeDirectory(UserService.java:353) ~[classes/:3.5.0-beta-1]
        at org.kitodo.production.helper.WebDav.uploadFromHome(WebDav.java:131) ~[classes/:3.5.0-beta-1]
        at org.kitodo.production.services.data.ProcessService.deleteSymlinksFromUserHomes(ProcessService.java:2329) ~[classes/:3.5.0-beta-1]
        at org.kitodo.production.services.data.ProcessService.deleteMetadataDirectory(ProcessService.java:2305) ~[classes/:3.5.0-beta-1]
        at org.kitodo.production.services.data.ProcessService.deleteProcess(ProcessService.java:2280) ~[classes/:3.5.0-beta-1]
        at org.kitodo.production.services.data.ProcessService.deleteProcess(ProcessService.java:2271) ~[classes/:3.5.0-beta-1]
        at org.kitodo.production.forms.DesktopForm.deleteProcess(DesktopForm.java:134) ~[classes/:3.5.0-beta-1]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
       ...
```

I have used the user "ccsccsadmin", which has the following access rights:
```
root@cloutodoproduction01testclone:/usr/local/kitodo/users# ll
total 24
drwxrwxrwx  6 tomcat tomcat 4096 Jul 28  2021 ./
drwxrwxrwx 17 root   root   4096 Nov 23 09:47 ../
drwxrwx---  2 tomcat tomcat 4096 Apr 26  2022 ccsccsadmin/
...
```

--> Please clarify

**Comment by solth** [comment] 2022-11-23 10:50
Duplicate of #5120

**Closed by solth** 2022-11-23 10:50 UTC
Labels: bug
