### ISSUE TITLE
Correction of the click way for the allocation of one page to two structure elements

### ISSUE THREAD

**Issue by subhhwendt** [kitodo/kitodo-production#3477] opened 2020-04-17 12:26 UTC
If you want to get the proper menu item ("Mit nächstem Element verknüpfen") by the right mousekey in the structure tree - you need to click at first at another place in the structure tree or to use the left mousekey for the chosen page before you can use the right mousekey with the complete expected menu
![grafik](https://user-images.githubusercontent.com/5708995/79568834-de49c080-80b6-11ea-91b0-1f45cc41415b.png)

**Comment by oliver-stoehr** [comment] 2020-04-20 06:54
Duplicate of #3470

**Closed** 2020-05-15 12:05 UTC
Labels: 3.x, bug
