### ISSUE TITLE
Using AddElement in meta data editor leads to Exception

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#3819] opened 2020-07-08 13:57 UTC
Version 3.2-build 16.09.2020:
If I use the addElement function in meta data editor (extended structure) I get an exception.
Attached you can find the rule set and some screen shots.
Please clarify.
![addElement](https://user-images.githubusercontent.com/61045115/86927129-37177b00-c133-11ea-8785-e6784e0d31da.png)
![addElement-2](https://user-images.githubusercontent.com/61045115/86927243-63cb9280-c133-11ea-80b0-18003ff33839.png)
![addElement-3](https://user-images.githubusercontent.com/61045115/86927244-64642900-c133-11ea-9acd-4afe7fb398ad.png)
[ruleset_CCS_min-Structure-v2.txt](https://github.com/kitodo/kitodo-production/files/4891047/ruleset_CCS_min-Structure-v2.txt)

**Comment by stefanCCS** [comment] 2020-07-08 14:08
Tested with "normal" (not-extended) meta data editor --> there is NO exception!

**Comment by solth** [comment] 2020-08-05 08:30
This may be related to or even a duplicate of #3444

**Comment by stefanCCS** [comment] 2020-08-13 09:03
When I get a newer version, I will test this again.

**Comment by stefanCCS** [comment] 2020-08-14 09:41
Tested again with version
3.2-build-14.08.2020
Same behaviour with the following exception:
![AddElementException-3819](https://user-images.githubusercontent.com/61045115/90236420-0b1ea200-de23-11ea-8210-5a03fa5b5ecc.png)

**Comment by Kathrin-Huber** [comment] 2020-08-20 08:12
fixed by #3944

**Closed by Kathrin-Huber** 2020-08-20 08:12 UTC
Labels: 3.x, bug
