### ISSUE TITLE
Links in the home directory cannot be removed

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3484] opened 2020-04-20 11:11 UTC
### Problem
Links to processes in the home directory (kitodo_preview/home) cannot be removed by any function (KitidoScript, action in process list). 

### Solution 
The link in the home directory should be removable.

**Comment by solth** [comment] 2020-04-20 11:16
Probably a duplicate of #3088

**Closed** 2020-04-29 20:00 UTC
Labels: 3.x, bug, duplicate
