### ISSUE TITLE
Deleted process templates in projects settings cannot be assigned again 

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#4570] opened 2021-08-11 12:14 UTC
### Problem
If a process template is deleted in the settings of a projects, it cannot be assigned again, because it is not shown anymore in the list "Add process templates". 

If no processes have been created with the process template, it is possible to assign the project to the in the "Template details". If processes have been created, the "Template details" cannot be changed. 

### Solution 
It should be possible to reassign process templates to a project after it was accidentally deleted. Otherwise, a new process template has be created.

**Comment by solth** [comment] 2021-08-11 17:26
This is perhaps a duplicate of #4152

**Comment by andre-hohmann** [comment] 2021-08-12 05:22
Yes you are right. That seems to be same problem.

**Comment by matthias-ronge** [comment] 2021-08-12 06:10
Yes, this is the same problem.

**Closed** 2021-08-13 05:03 UTC
Labels: duplicate, 3.x
