### ISSUE TITLE
"Set status of process down" does not work correctly

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#4723] opened 2021-10-07 13:01 UTC
### Problem
If the status of a process is set down via the "possible actions" in the process list, the task with the highest id is set down. In many cases, this is not the last task of the process and the task status of the tasks are quite confusing (see examples below). 

### Solution
If a status is set down, the ordering number should be regarded for the order to set down the tasks. 

Probably related to #4575.

#### Task status after setting down in "Edit process"

Initial state: all tasks were were closed (=green)

![Zurücksetzen01](https://user-images.githubusercontent.com/14835770/136389050-70dc1013-9129-4344-b621-9d9e342c49ff.jpg)

#### Task status after setting down in the database
![Zurücksetzen02](https://user-images.githubusercontent.com/14835770/136388930-b0cae345-ab6e-484b-8c7f-c498d32ff26c.jpg)

**Comment by matthias-ronge** [comment] 2021-10-11 06:43
I see that #3575 was a duplicate of this.

**Closed as completed** 2021-10-20 07:42 UTC
Labels: bug
