### ISSUE TITLE
Task cannot be accepted

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3613] opened 2020-05-11 04:52 UTC
### Problem
Tasks in the task list cannot be accepted. If the the bell-icon is clicked, the following message is shown: 
- "Error... An error has occurred."

**Comment by solth** [comment] 2020-05-13 06:44
This is a duplicate of #3615 Both originate from the fact that `blockedUser` has been removed.

**Comment by solth** [comment] 2020-05-13 09:48
Fixed by #3618

**Closed by solth** 2020-05-13 09:48 UTC
Labels: 3.x, blocking, bug
