### ISSUE TITLE
Creation of processes for volumes of multivolume works is not possible

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3416] opened 2020-04-08 14:36 UTC
### Problem
It is not possible to create processes for volumes of multivolume works. There are two options working wrongly in different ways. 

#### Option 1: import dephts =2
It is possible to 
- Search the opac
- Import the metadata
- Generate the process title

It is not possible to: 
- Save the process -> After clicking "Save" the massage "validata data" is shown, then nothing happens. 

#### Option 1: import dephts =1
It is possible to 
- Search the opac
- Import the metadata
- Generate the process title
- Save the process 

However, only the process for the volume is created. Thus, there is no linking to the parent process. 

#### Example-PPN of the volumes of multivolume works:
- 1428576223
- 142865559X
- 1449010784
- 142132640X
- 1421324458

### Solution
It should be possible to create processes for the volumes of multivolume works. 

See also the following issues:
- https://github.com/kitodo/kitodo-production/pull/3287
- https://github.com/kitodo/kitodo-production/issues/3257

**Comment by solth** [comment] 2020-04-09 15:37
The first option (with import depth=2) produces a NullPointerException with the following partial stack trace:
```
 java.lang.NullPointerException
        at org.kitodo.production.forms.createprocess.ProcessFieldedMetadata.getMetadata(ProcessFieldedMetadata.java:441)
        at org.kitodo.production.forms.createprocess.ProcessFieldedMetadata.preserve(ProcessFieldedMetadata.java:520)
        at org.kitodo.production.services.data.ImportService.transformToProcessDetails(ImportService.java:830)
        at org.kitodo.production.services.data.ImportService.processTempProcess(ImportService.java:1024)
        at org.kitodo.production.forms.createprocess.CreateProcessForm.processAncestors(CreateProcessForm.java:471)
        at org.kitodo.production.forms.createprocess.CreateProcessForm.createProcessHierarchy(CreateProcessForm.java:368)
        at org.kitodo.production.forms.createprocess.CreateProcessForm.createNewProcess(CreateProcessForm.java:286)
```
@matthias-ronge isn't this something you fixed not very long ago?

**Comment by matthias-ronge** [comment] 2020-04-15 09:58
This error occurs because the ruleset has a `<restriction division="MultiVolumeWork" unspecified="forbidden">` which does not `<permit key="slub_serialGroup">`, but the imported data contains a metadata group “`slub_serialGroup`”. Nevertheless, the ruleset should be tolerant of this, which it is not at the moment. This needs to be fixed.

**Comment by andre-hohmann** [comment] 2020-04-15 11:34
I think an error- or warning-message describing the problem would be appropriate. 

We have still the discussion, how to cope with differing metadata between import and ruleset. However, that will be discussed in another issue.

**Comment by matthias-ronge** [comment] 2020-04-16 07:43
Closed as currently not reproducible.

**Closed by matthias-ronge** 2020-04-16 07:43 UTC
Labels: 3.x, blocking, bug
