### ISSUE TITLE
Multiple xlink:to elements for one xlink:from element in mets:structLink

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#5286] opened 2022-08-11 13:01 UTC
**Describe the bug**
In Kitodo.Production 3.x multiple `xlink:to` elements are assigned to one `xlink:from` element in `<mets:structLink>`. 
This happens for the element that are assigned to several structure elements. 
In the DFG-Viewer, this leads to the multiple depiction of the metadata of the selected elements. See example in "Additional context". 

**To Reproduce**
1. Examination of the exported METS file of a process with several structure elements on different levels. 

**Expected behavior**
One `xlink:to` element should be assigned to one `xlink:from` element only once

**Release**
- 3.4.4-SNAPSHOT

**Desktop (please complete the following information):**
- OS: Windows 10
- Chrome 103.0.5060.134 (Offizieller Build) (64-Bit)

**Additional context**

1 Example in DFG-Viewer (SUB): 
- https://dfg-viewer.de/show?id=9&tx_dlf%5Bid%5D=http%3A%2F%2Fmets.sub.uni-hamburg.de%2Fkitodo%2FPPN1773384848&tx_dlf%5Bpage%5D=471

The metadata fields "Titel", "Autor", "Einrichtung", ... are doubled, when structure elements on lower level are selected - in this case: Image 471. 

2 Comparison of the `<mets:structLink>` of another process (SLUB)
- a `<mets:structLink>` in Kitodo.Production 3.x - internal METS-file

<details>

``` xml
    <mets:structLink>
        <mets:smLink xlink:to="PHYS_0001" xlink:from="LOG_0001"/>
        <mets:smLink xlink:to="PHYS_0002" xlink:from="LOG_0001"/>
        <mets:smLink xlink:to="PHYS_0003" xlink:from="LOG_0001"/>
        <mets:smLink xlink:to="PHYS_0004" xlink:from="LOG_0001"/>
        <mets:smLink xlink:to="PHYS_0005" xlink:from="LOG_0004"/>
        <mets:smLink xlink:to="PHYS_0006" xlink:from="LOG_0005"/>
        <mets:smLink xlink:to="PHYS_0007" xlink:from="LOG_0005"/>
        <mets:smLink xlink:to="PHYS_0008" xlink:from="LOG_0007"/>
    </mets:structLink>
```
</details>

- b `<mets:structLink>` in Kitodo.Production 3.x - external METS-file

<details>

``` xml
   <mets:structLink>
      <mets:smLink xlink:to="PHYS_0001" xlink:from="LOG_0000"/>
      <mets:smLink xlink:to="PHYS_0002" xlink:from="LOG_0000"/>
      <mets:smLink xlink:to="PHYS_0003" xlink:from="LOG_0000"/>
      <mets:smLink xlink:to="PHYS_0004" xlink:from="LOG_0000"/>
      <mets:smLink xlink:to="PHYS_0005" xlink:from="LOG_0000"/>
      <mets:smLink xlink:to="PHYS_0006" xlink:from="LOG_0000"/>
      <mets:smLink xlink:to="PHYS_0007" xlink:from="LOG_0000"/>
      <mets:smLink xlink:to="PHYS_0005" xlink:from="LOG_0000"/>
      <mets:smLink xlink:to="PHYS_0006" xlink:from="LOG_0000"/>
      <mets:smLink xlink:to="PHYS_0007" xlink:from="LOG_0000"/>
      <mets:smLink xlink:to="PHYS_0008" xlink:from="LOG_0000"/>
      <mets:smLink xlink:to="PHYS_0008" xlink:from="LOG_0000"/>
      <mets:smLink xlink:to="PHYS_0005" xlink:from="LOG_0000"/>
      <mets:smLink xlink:to="PHYS_0006" xlink:from="LOG_0000"/>
      <mets:smLink xlink:to="PHYS_0007" xlink:from="LOG_0000"/>
      <mets:smLink xlink:to="PHYS_0005" xlink:from="LOG_0000"/>
      <mets:smLink xlink:to="PHYS_0006" xlink:from="LOG_0000"/>
      <mets:smLink xlink:to="PHYS_0007" xlink:from="LOG_0000"/>
      <mets:smLink xlink:to="PHYS_0008" xlink:from="LOG_0000"/>
      <mets:smLink xlink:to="PHYS_0008" xlink:from="LOG_0000"/>
      <mets:smLink xlink:to="PHYS_0001" xlink:from="LOG_0001"/>
      <mets:smLink xlink:to="PHYS_0002" xlink:from="LOG_0001"/>
      <mets:smLink xlink:to="PHYS_0003" xlink:from="LOG_0001"/>
      <mets:smLink xlink:to="PHYS_0004" xlink:from="LOG_0001"/>
      <mets:smLink xlink:to="PHYS_0005" xlink:from="LOG_0002"/>
      <mets:smLink xlink:to="PHYS_0006" xlink:from="LOG_0002"/>
      <mets:smLink xlink:to="PHYS_0007" xlink:from="LOG_0002"/>
      <mets:smLink xlink:to="PHYS_0005" xlink:from="LOG_0002"/>
      <mets:smLink xlink:to="PHYS_0006" xlink:from="LOG_0002"/>
      <mets:smLink xlink:to="PHYS_0007" xlink:from="LOG_0002"/>
      <mets:smLink xlink:to="PHYS_0008" xlink:from="LOG_0002"/>
      <mets:smLink xlink:to="PHYS_0008" xlink:from="LOG_0002"/>
      <mets:smLink xlink:to="PHYS_0005" xlink:from="LOG_0003"/>
      <mets:smLink xlink:to="PHYS_0006" xlink:from="LOG_0003"/>
      <mets:smLink xlink:to="PHYS_0007" xlink:from="LOG_0003"/>
      <mets:smLink xlink:to="PHYS_0005" xlink:from="LOG_0004"/>
      <mets:smLink xlink:to="PHYS_0006" xlink:from="LOG_0005"/>
      <mets:smLink xlink:to="PHYS_0007" xlink:from="LOG_0005"/>
      <mets:smLink xlink:to="PHYS_0008" xlink:from="LOG_0006"/>
      <mets:smLink xlink:to="PHYS_0008" xlink:from="LOG_0007"/>
   </mets:structLink>
```
</details>

- c `<mets:structLink>` in Kitodo.Production 2.x

<details>

``` xml
    <mets:structLink>
        <mets:smLink xlink:to="PHYS_0001" xlink:from="LOG_0000" ></mets:smLink>
        <mets:smLink xlink:to="PHYS_0002" xlink:from="LOG_0000" ></mets:smLink>
        <mets:smLink xlink:to="PHYS_0003" xlink:from="LOG_0000" ></mets:smLink>
        <mets:smLink xlink:to="PHYS_0004" xlink:from="LOG_0000" ></mets:smLink>
        <mets:smLink xlink:to="PHYS_0005" xlink:from="LOG_0000" ></mets:smLink>
        <mets:smLink xlink:to="PHYS_0006" xlink:from="LOG_0000" ></mets:smLink>
        <mets:smLink xlink:to="PHYS_0007" xlink:from="LOG_0000" ></mets:smLink>
        <mets:smLink xlink:to="PHYS_0008" xlink:from="LOG_0000" ></mets:smLink>
        <mets:smLink xlink:to="PHYS_0001" xlink:from="LOG_0001" ></mets:smLink>
        <mets:smLink xlink:to="PHYS_0002" xlink:from="LOG_0001" ></mets:smLink>
        <mets:smLink xlink:to="PHYS_0003" xlink:from="LOG_0001" ></mets:smLink>
        <mets:smLink xlink:to="PHYS_0004" xlink:from="LOG_0001" ></mets:smLink>
        <mets:smLink xlink:to="PHYS_0005" xlink:from="LOG_0002" ></mets:smLink>
        <mets:smLink xlink:to="PHYS_0006" xlink:from="LOG_0002" ></mets:smLink>
        <mets:smLink xlink:to="PHYS_0007" xlink:from="LOG_0002" ></mets:smLink>
        <mets:smLink xlink:to="PHYS_0008" xlink:from="LOG_0002" ></mets:smLink>
        <mets:smLink xlink:to="PHYS_0005" xlink:from="LOG_0003" ></mets:smLink>
        <mets:smLink xlink:to="PHYS_0006" xlink:from="LOG_0003" ></mets:smLink>
        <mets:smLink xlink:to="PHYS_0007" xlink:from="LOG_0003" ></mets:smLink>
        <mets:smLink xlink:to="PHYS_0005" xlink:from="LOG_0004" ></mets:smLink>
        <mets:smLink xlink:to="PHYS_0006" xlink:from="LOG_0005" ></mets:smLink>
        <mets:smLink xlink:to="PHYS_0007" xlink:from="LOG_0005" ></mets:smLink>
        <mets:smLink xlink:to="PHYS_0008" xlink:from="LOG_0006" ></mets:smLink>
        <mets:smLink xlink:to="PHYS_0008" xlink:from="LOG_0007" ></mets:smLink>
    </mets:structLink>
```
See: https://digital.slub-dresden.de/oai?verb=GetRecord&metadataPrefix=mets&identifier=oai:de:slub-dresden:db:id-31209907X

</details>

- d Screenshot of the structrure tree in the  metadata editor

![BeispielStructLink2](https://user-images.githubusercontent.com/14835770/184354524-3992dba5-61df-4851-afac-e652913b710d.jpg)

**Comment by BartChris** [comment] 2022-08-12 12:06
I have not yet encountered the behaviour but if this happens it would be a quite critical bug. In order to replicate that behaviour i would like to know:

- Does this behaviour only appear in the exported METS? Or are there already problems with the meta.xml inside of Kitodo?
- "This happens for the element that are assigned to several structure elements." - do you mean pages which are assigned to multiple strucural elements?

**Comment by andre-hohmann** [comment] 2022-08-12 12:42
1. As far as I know, the behavior occurs only in the exported METS file. 
I added the `<mets:structLink>` of the internal METS-file in the issue (2a). 
2. It seems as if occurs, when files are assigned to multiple structure elements. For example, `PHYS_0005` occurs four times for `LOG_0000` - same do `PHYS_0006`, `PHYS_0007` and `PHYS_0008`. `PHYS_0001` - `PHYS_0004` occur only once in `LOG_0000` (Although i would expect the to occur twice - but maybe i cannot count correctly anymore). The function "Assign to next element" cannot be the reason for this behavior. 
I added a screenshot of the structure tree in the metadata editor in the issue (2d).

**Comment by andre-hohmann** [comment] 2022-08-12 13:21
Probably, Kitodo.Production cannot cope correctly with the structure elements of the intermediate layers during the export. 

For the structure elements without assigned image files, the files from the subordinate structure elements are assigned. It seems, as if the files are summed up for each level or layer. The intermediate layer however, should not be regarded.

**Comment by BartChris** [comment] 2022-08-12 13:44
I suspect something along those lines as well. It seems as if Kitodo is generating one entry in the respective upper layer for every sublayer. In you example you have four sub layers unti you reach page 0005. Which leads to four entries which link the root layer to page 0005.

The rule should be that the top element should contain all the elements of all the sub-layers, but should not add them up. If the root element has three sublayers, than all those layers have a reference to the image, but

**Comment by BartChris** [comment] 2022-08-12 15:34
I investigated further and i think the problem is on those lines:

https://github.com/kitodo/kitodo-production/blob/master/Kitodo/src/main/java/org/kitodo/production/metadata/MetadataEditor.java#L361-L367

It seems to me that for every sub level the same page is added again to the list. I therefor replaced the ArrayList with a `LinkedHashset` and this seems to resolve the issue. I will prepare a pull request so that it can be evaluated if this is the correct fix:

`private static Collection<View> getViewsFromChildrenRecursive(LogicalDivision structure) {
        Set<View> viewsFromChildren = new LinkedHashSet<>(structure.getViews());
        for (LogicalDivision child : structure.getChildren()) {
            viewsFromChildren.addAll(getViewsFromChildrenRecursive(child));
        }
        return viewsFromChildren;
    }`

**Comment by matthias-ronge** [comment] 2022-08-15 07:29
Yes, exported METS must have links to all linked elements on all levels, while internally, Production only stores links to the lowest level where media is linked. (Otherwise, you would see all those duplicate links showing in the metadata editor gallery, too.) Therefore, the links are reduplicated during export. Of course, duplicating existing links is wrong.

**Closed** 2022-08-22 12:30 UTC
Labels: bug
