### ISSUE TITLE
Changes in the process properties cannot be saved

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#4825] opened 2021-11-15 10:53 UTC
### Problem
If process properties, the task status (via task list), ... of a process are changed and saved, an error message occurs and the changes cannot be saved: 
- `The process title 'XXXXXXXXXX' is already in use.`

Only changes in the task details can be saved.

### Solution
It should be possible to change the process properties, the task status via the task list, ... and to save the changes. 

I am sure that this was possible in the earlier versions

**Comment by solth** [comment] 2021-11-15 11:50
Duplicate of #4815

**Closed** 2021-11-15 11:53 UTC
Labels: duplicate, 3.x
