### ISSUE TITLE
Erweiterter Strukturbaum only available in tasklist

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3567] opened 2020-04-30 13:53 UTC
### Problem
If the "Erweiterter Strukturbaum" is configured in the applied workflow, it is only shown, when the process is opened in the metadata editor from the task list. 
If the metadata editor is opened from the process list or from the list of the simple search, the "Einfacher Strukturbaum" is shown. 

### Solution
If the "Erweiterter Strukturbaum" is configured in the workflow, it should always been shown in the metadata editor.

**Comment by solth** [comment] 2020-05-04 12:18
I think this is related to #3524. When opened via the task details page, the `currentTask` - which defines which whether the separate or combined structure tree is displayed - is set correctly to the task to which the current detail page belongs. 

When the metadata editor is opened via the process list on the other hand, the current task is sometimes not set correctly (for example, if an admin to which none of the currently open tasks is assigned opens the process in the metadata editor), resulting in the metadata editor trying to determine a "fallback" task, which is normally just the first task in the workflow. If for that task the separate tree is not configured, the combined tree will be displayed instead.

**Comment by Kathrin-Huber** [comment] 2020-05-05 14:36
But we have the restrictions, that every task needs to have the same configuration, so this shouldn't be a problem.

**Comment by solth** [comment] 2020-05-05 15:17
> But we have the restrictions, that every task needs to have the same configuration, so this shouldn't be a problem.

It isn't - for determining whether the combined structure tree should be shown or the separate structure tree! 

But for setting the `currentTask` to which the workflow will return until a correction has been completed task configuration in the workflow is of no help.

These are two separate purposes for which `currentTask` is/was used, and only the first purpose would be fixed by the proposed changes.

**Comment by andre-hohmann** [comment] 2020-05-11 06:05
Additional information: 
If the status of the process is `inwork`, the "Erweiterter Strukturbaum" can be opened also from the process list. 
If the status of the process is `open`, it is not possible.

**Comment by solth** [comment] 2020-05-20 08:25
> Additional information:
> If the status of the process is `inwork`, the "Erweiterter Strukturbaum" can be opened also from the process list.
> If the status of the process is `open`, it is not possible.

The reason for this is that at the moment only tasks that are `inwork` by the current user are considered `current tasks` and used to determine the structure tree mode. If such a task is found its `separateMedia` flag will be used to determine whether the combined or separated structure tree should be shown. 

If there are only `open` tasks, but no `inwork` tasks, the structure tree configuration is resolved by reading the configuration of the first task in the workflow (the "fallback task") to determine the mode. 

Apparently, this does not work as intended at the moment and the structure tree instead resolves to the combined mode as a default, which seems to be the acutal bug in this scenario.

**Closed** 2020-05-26 06:36 UTC
Labels: 3.x, bug
