### ISSUE TITLE
Close metadata editor without saving raises no warning?

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4821] opened 2021-11-11 13:30 UTC
We have observed that if you have been working in the metadata editor, then you close with the "Close" button, it goes away, but there is no warning of the form: "Do you want to exit without saving?" This is functionally correct, but we were surprised because we felt we were expecting a warning pop-up.

**Question:** Is that intended? Should we include a warning, or is it fine without?

**Comment by andre-hohmann** [comment] 2021-11-12 07:50
In my opinion the warning would be helpful, when it really appears only after changes have been made. If it appears always, i think it will be annoying. I often open the metadata editor to examine the metadata without changing anything. 

As in Kitodo.Production 2.x no warning appears, i think that most users are used to the behaviour without a warning message. I never heard that this has caused loss of metadata. Thus, for me it is not of high priority. 

Maybe there are other experiences in other institutions.

**Comment by matthias-ronge** [comment] 2021-11-16 14:29
Yes, I only meant when something was actually changed.

It looks like this is a bug. There is such functionality implemented (Variable `workpieceOriginalState` in class `DataEditorForm`) but it doesn’t work under all circumstances.

I added the <kbd>invalid</kbd> label because the error description is too imprecise (I first have to test exactly which changes are not correctly noticed; unfortunately I don't know anymore either).

**Comment by solth** [comment] 2023-02-11 18:13
In my opinion it is not a bug that the warning does _not_ appear when the user closes the metadata editor explicitely using the "Close" button, because it suggests he discarded changes deliberately, IMHO. At least that is how it is implemented right now. 
Instead, atm the warning is implemented to only be shown if the user closes the editor by any other means (clicking another link like the a breadcrumb link or the Kitodo logo in the upper left, manually entering a new URL in the browsers address field or closing the tab/browser altogether).

This behaviour is still bugged at the moment, though, because the warning currently often occurs even when the user did not actually make any changes to the workpiece at all.
After analysing the current behavior, I found out that the follwoing two actions cause this wrong "Unsaved changes" warning dialog:
- the user selects a structure by clicking on the corresponding node in the structure tree or gallery stripe in the gallery.  Reason: the `group` property of `MetadataGroup` instances in the `workpiece` variable of `DataEditorForm` is set to `ArrayList<Metadata>` when the user clicks a structure element, whereas the corresponding `group` properties in `workpieceOriginalState` are of type `HashSet<Metadata>`. The method `MetadataGroup.equals` (which is used for detecting changes) compares - among others - the class of the `group` property, resulting in `workpiece` and `workpieceOriginalState` being evaluated as different
- the user clicks on an unpaginated page/media in the structure tree or gallery. Reason: when a page is first saved to the workpiece without explicit pagination, it's `ORDERLABEL` attribute will be set to ` - ` (**with** leading and trailing whitespace). When selecting the page in the metadata editor once (without paginating/changing it), the `ORDERLABEL` is set to `-` (**without** leading or trailing whitespace), which again results in the `workpiece` and `workpieceOriginalState` being evaluated as differenct.

I opened a pull request to fix these two errors: #5536

**Comment by solth** [comment] 2023-07-04 09:36
@kitodo/kitodo-community-board is the current behaviour described in my comment above sufficient in your opinion or should the implementation be changed to also display the "Warning" dialog when explicitly closing the metadata editor with unsaved changes via the "Close" button?

**Comment by subhhwendt** [comment] 2023-07-19 11:45
We discussed this issue in the community board and we can confirm that the current behaviour of the button is the expected one.

**Closed** 2023-07-19 11:56 UTC
Labels: invalid, metadata editor
