### ISSUE TITLE
Permission or Way to see all processes in a system / Processes not deleted

### ISSUE THREAD

**Issue by mnscholz** [kitodo/kitodo-production#3580] opened 2020-05-05 06:36 UTC
When deleting a process, the process consistently is removed from GUI, but sometimes remains in DB. I have no clue why. I am missing a way, eg. a role permission, to make DB entries visible, no matter who they belong to etc.

Long story:
I tidied up my Kitodo test installation and removed some 20 processes by clicking the trash button.
While all disappeared from the GUI, 4 still remain in the MySQL DB. The statistics tab in the GUI and the indexing tab also show 6 processes!
In the DB table entries, I can see no nothing that would make the entry "deleted" or "invisible".
I suspect that te processes have lost the association to me as a user.

Is there a way to make them visible again and cleanly remove them? Does Kitodo have some concept of superuser / role that shows all processes, projects, etc.?
Currently I see no way of getting rid of these processes other than sql-deleting them.

Although the removed processes don't appear on the GUI, they have effects on it: eg. they prohibit further tidying up as projects associated with these processes can't be removed.

**Comment by matthias-ronge** [comment] 2020-05-05 09:29
The first thing I would try is to rebuild the search engine index. To do this, you have to go to System Indexing, delete ElasticSearch mapping, then recreate ElasticSearch mapping, and index everything. Then logout and login again.

If that doesn't help, can you provide us with the database as a [Gist](https://gist.github.com/)? Then we can have a look to see what the situation is now and then find out how it came to this.

**Comment by mnscholz** [comment] 2020-05-05 10:19
Rebuilding the ES index does not change anything. I rebuilt it twice. The first time, the rebuild got stuck / crashed. After restarting Tomcat the reindexing went fine.

The process table is uploaded here as a sql dump: https://gist.github.com/mnscholz/1ff8d8d0d68b2a8cf889ebc5a2ac0ffd 
If you need more data, I would be happy to provide it.

**Comment by Kathrin-Huber** [comment] 2020-05-05 13:46
the reindexing still leads to a 0/4 state at the end of the indexing line?
This would also be my recommendation to rebuild the index. Everything which is in Database is written to index and therefore shown in the frontend.

**Comment by mnscholz** [comment] 2020-05-05 17:50
I'm sorry, I wasn't clear about the reindexing: After reindexing, the line says: "6 / 6" (this makes sense as there are 2 regular processes and 4 "deleted" ones). That is, Kitodo seems to find and index the "deleted" processes, but it doesn't show them anymore. 

That's why I assume, the processes just lost the association to their user (me) and that's why I ask for the possibility/permission to see all processes.

**Comment by matthias-ronge** [comment] 2020-05-06 06:50
The process table looks undamaged. But it can also be due to something else.

To answer your initial question: To make everything visible and possible to your user, the following should be the case:
- Assign your user to all clients. (in settings of your user)
- Assign all projects to your user. (in settings of your user)
- Activate all projects. (in settings of each project)
- (for permissions: create a role with all permissions and assign this role to your user)

To be sure, log out and back in again after this.

That is what I can think of. However, I suspect this is a bug when deleting because after deleting the process is no longer visible, this is the expectation. Deleted processes should remove from database, so it is wrong if they don’t.

**Comment by mnscholz** [comment] 2020-05-06 08:29
The four steps don't make the four "deleted" processes visible again.

I will try to make this behaviour reproducible.

**Comment by matthias-ronge** [comment] 2020-08-10 14:16
I'll assign the <kbd>invalid</kbd> marking here as long as the behavior is not reproducible. Otherwise this would have to be classified as a <kbd>bug</kbd> again.

**Comment by Kathrin-Huber** [comment] 2022-06-16 14:12
Please reopen, if this is a problem again

**Closed by Kathrin-Huber** 2022-06-16 14:12 UTC
Labels: invalid, 3.x
