### ISSUE TITLE
Scroll-panel for images in metadata editor does not work correctly

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#5670] opened 2023-05-24 09:09 UTC
**Describe the bug**
In the "detail view" of the metadata editor, the scroll-panel on the rights side does not work correctly. 
~~1. If an image is selected in the scroll-panel, no image is shown in the "Detail view", but the image in the structure tree is selected. Therefore, it is possible/necessary to click additionally the image in the structure tree to show the image file in the "detail view".~~ 
Solved by: 
- #5655

2. If the image is selected in the structure tree, the correct image is shown in the detail view, but the scroll-panel shifts to the last images. 
3. If an image is selected in the scrollbar, the selected images in the scroll-panel stays not in focus, but the first image is shown again. 
Therefore it is necessary to scroll back to the selected image in the scroll-panel. 

See GIF below. 

**To Reproduce**
1. Open the metadata editor 
3. Go to "detail view"
5. Scroll down to an image in the panel and select it

**Expected behavior**
If an image in the sin the panel is selected, 
1. ~~the selected image should be shown directly in the detail view.~~
Solved by: 
- #5655
2. the sin the panel  should always be in focus of the selected image and should not shift to the beginning or the end of the scrollbar. 

**Screenshots**
![ScrollbarMetadateneritor](https://github.com/kitodo/kitodo-production/assets/14835770/f54a788f-04fe-41c2-9569-8e80df02daa2)

**Release**
KITODO.PRODUCTION Version 3.6.0-SNAPSHOT

**Desktop (please complete the following information):**
 - Windows
 - Chrome

**Comment by solth** [comment] 2023-05-24 09:34
This reads very much like a duplicate of https://github.com/kitodo/kitodo-production/issues/5652 which was fixed by https://github.com/kitodo/kitodo-production/pull/5655. But you are right, I just encounted the same problem in the current state of the master branch today, again.

**Comment by solth** [comment] 2023-05-24 09:48
I just checked the current version again and it seems this was again a caching problem. Reloading the whole metadata editor _with_ the cache updates the corresponding Javascript file `ol_custom.js`. After that, the large image in the "Detail View" is updated correctly when clicking a thumbnail in the corresponding scroll panel. 

The other two problems you described concerning the scroll position of this scroll panel do seem to still persist. @andre-hohmann can you check whether reloading the metadata including the cache does at least resolve the first issue concerning the missing detail view for you as well?

**Comment by andre-hohmann** [comment] 2023-05-24 12:44
@solth : Thanks a lot!
The problem was not only the famous cache. We apply the master version from 01.03.2023 with some additional PR to prevent possible regressions by other developments - a preparation for the migration. 

However, PR #5655 is very helpful and at least problem number 1 is solved. Number 2 and 3 do still exist.

**Comment by thomaslow** [comment] 2023-05-27 11:17
Hi André, I investigated the scroll problem a bit, thinking it might be related to the implementation of the performance improvements of the meta data editor that I did in 2022. I followed the problem to the pull request #5472. Immediately before that, scrolling worked fine. After that, scrolling didn't work anymore.

@markusweigelt Hi Markus, the problem seems to be related to your refactoring of the gallery into the "media list" template. You added an update command to the gallery component that will refresh the "mediaDetailContainer", effectively reloading all thumbnails in the vertical list, which will prevent the scrolling from working, see:

https://github.com/kitodo/kitodo-production/blob/5425b6f2e330d58df0b4ce1059549f264127fae0/Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/gallery.xhtml#L40

In addition, this also partially reverts the performance improvements of the meta data editor. The idea was to not do expensive reloads of potentially very large thumbnail lists in case the user only selects things, which doesn't really affect the user interface much (other than scrolling to and highlighting the selected elements).

Also, the div-container hierarchy of the gallery thumbnails was changed a bit, such that the Javascript that triggers the scrolling doesn't work anymore. I came up with a quick fix to the last problem, see https://github.com/kitodo/kitodo-production/commit/9fa6a8ac4cbc43f4900a44a058f14514c7c9df82. However, I do not intent to continue working on the problem, since it is clearly related to #5472. Still, I hope my feedback helps to solve this issue.

**Comment by solth** [comment] 2023-05-27 11:36
@thomaslow thanks a lot for your analysis. I also had a quick look at the problem and reached the same line in the `update` attribute that you mentioned above. Just changing `imagePreviewForm:mediaDetailContainer` to `imagePreviewForm:mediaDetail` (https://github.com/effective-webwork/kitodo-production/tree/preview-scrolling) also seems to at least partly mitigate the reported issue, because clicking on a thumbnail in the detail views thumbnail stripe itself does not update the scroll position anymore.

@markusweigelt perhaps it's possible to resolve the issue with the desribed approaches.

**Comment by thomaslow** [comment] 2023-05-30 17:34
> Do you mean this connection with this bug or are you referring to the entire refactoring / combining of repeating components?

@markusweigelt I was referring to the update declaration for the `imagePreviewForm:mediaDetailContainer` in the `sendGallerySelect` remote command. Your pull request might fix that. I haven't tested it (yet).

The `sendGallerySelect` remote command is executed whenever a user selects any thumbnail. Before the performance improvement, this was triggering a full reload of both the logical/physical tree as well as the gallery via a PrimeFaces AJAX call such that the new selection state was synchronized between the tree component and the gallery, and appropriate tree nodes and thumbnails were correctly styled with highlighted borders around them. 

For large processes with 1000 or more thumbnails, this was very slow. The AJAX call would take a long time to load, and the browser (especially on old machines) was busy deleting and re-adding thousands of DOM elements, multiple elements for each tree node and thumbnail. 

Since selecting something doesn't change the user interface much, the performance improvement (see #5147) added special Javascript that would update the selection (borders around thumbnail) without the need to do a full reload of the logical/physical tree and gallery.

**Closed** 2023-06-02 16:18 UTC
Labels: bug, metadata editor
