### ISSUE TITLE
Select several elements in the structure tree

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4199] opened 2021-02-18 09:12 UTC
In the gallery it is possible to select several images with <kbd>Ctrl</kbd> + click. In the same way it should be possible to select several divisions in the structure map tree (for example, because you want to delete them all at once).

**Comment by solth** [comment] 2021-02-18 10:55
Duplicate of #3629

**Closed** 2021-02-24 07:48 UTC
Labels: 3.x, duplicate, improvement
