### ISSUE TITLE
Long running newspaper batch exports failed

### ISSUE THREAD

**Issue by henning-gerhardt** [kitodo/kitodo-production#472] opened 2016-06-06 12:31 UTC
A newspaper batch export with over 7.400 processes failed with an JDBC connection exception:

```
java.lang.RuntimeException: JDBCConnectionException while exporting DresVo_416951805-19240821: could not prepare statement
    at de.sub.goobi.helper.tasks.ExportNewspaperBatchTask.run(ExportNewspaperBatchTask.java:275)
Caused by: org.hibernate.exception.JDBCConnectionException: could not prepare statement
    at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:67)
    at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
    at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:124)
    at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:193)
    at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:157)
    at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1881)
    at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1858)
    at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1838)
    at org.hibernate.loader.Loader.doQuery(Loader.java:906)
    at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:348)
    at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:318)
    at org.hibernate.loader.Loader.loadCollection(Loader.java:2262)
    at org.hibernate.loader.collection.CollectionLoader.initialize(CollectionLoader.java:65)
    at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:674)
    at org.hibernate.event.internal.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:86)
    at org.hibernate.internal.SessionImpl.initializeCollection(SessionImpl.java:1810)
    at org.hibernate.collection.internal.AbstractPersistentCollection$4.doWork(AbstractPersistentCollection.java:552)
    at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:234)
    at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:548)
    at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:126)
    at org.hibernate.collection.internal.AbstractPersistentCollection$1.doWork(AbstractPersistentCollection.java:155)
    at org.hibernate.collection.internal.AbstractPersistentCollection$1.doWork(AbstractPersistentCollection.java:140)
    at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:234)
    at org.hibernate.collection.internal.AbstractPersistentCollection.readSize(AbstractPersistentCollection.java:139)
    at org.hibernate.collection.internal.PersistentSet.size(PersistentSet.java:156)
    at de.sub.goobi.export.download.ExportMets.writeMetsFile(ExportMets.java:272)
    at de.sub.goobi.export.dms.ExportDms.startExport(ExportDms.java:367)
    at de.sub.goobi.helper.tasks.ExportNewspaperBatchTask.run(ExportNewspaperBatchTask.java:267)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
    at com.mysql.jdbc.Util.getInstance(Util.java:387)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:917)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:896)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:885)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
    at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1235)
    at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1230)
    at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4132)
    at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4101)
    at com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:567)
    at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:159)
    at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:183)
    ... 24 more
```

It takes a very long time (over 10 minutes) until progress bar shows any change. Exporting every single process of this batch works without any problem. Batch export is started after first export with images and images are archived so only metadata files are exported.

**Comment by matthias-ronge** [comment] 2016-06-06 13:23
The connection was closed. There may be different reasons for this. Here are related questions:
* http://stackoverflow.com/q/7565143/1503237
* http://stackoverflow.com/q/32944222/1503237

Can you post the corresponding settings from your hibernate config file?

**Comment by henning-gerhardt** [comment] 2016-06-06 13:27
Which one did you need?

**Comment by henning-gerhardt** [comment] 2016-06-06 13:36
I added output of two files: c3p0.properties and hibernate.cfg.xml

c3p0.properties:
```text
c3p0.testConnectionOnCheckout=false
c3p0.preferredTestQuery = SELECT 1;
c3p0.debugUnreturnedConnectionStackTraces=true
c3p0.unreturnedConnectionTimeout=800
```

hibernate.cfg.xml
```xml
<property name="dialect">org.hibernate.dialect.MySQL5Dialect</property>
<property name="hibernate.connection.driver_class">com.mysql.jdbc.Driver</property>
<property name="hibernate.connection.url">
jdbc:mysql://*****/goobi?autoReconnect=true&amp;autoReconnectForPools=true
</property>
<property name="hibernate.connection.username">****</property>
<property name="hibernate.connection.password">****</property>
<property name="hibernate.c3p0.max_size">50</property>
<property name="hibernate.c3p0.min_size">2</property>
<property name="hibernate.c3p0.timeout">30</property>
<property name="hibernate.c3p0.max_statements">0</property>
<property name="hibernate.c3p0.idle_test_period">10</property>
<property name="hibernate.c3p0.acquire_increment">1</property>
<property name="hibernate.c3p0.validate">true</property>
<property name="hibernate.c3p0.unreturnedConnectionTimeout">800</property>
<property name="hibernate.c3p0.autoCommitOnClose">true</property>
<property name="hibernate.dbcp.validationQuery">select 1</property>
<property name="hibernate.dbcp.testOnBorrow">true</property>
<property name="hibernate.dbcp.testOnReturn">true</property>
<property name="connection.provider_class">org.hibernate.service.jdbc.connections.internal.C3P0ConnectionProvider</property>
<property name="current_session_context_class">managed</property>
<property name="show_sql">false</property>
<property name="hibernate.bytecode.use_reflection_optimizer">false</property>
<property name="hbm2ddl.auto">update</property>
```

**Comment by matthias-ronge** [comment] 2016-06-10 13:07
As I guess the database is running on *localhost*, we likely can exclude network issues as the cause. There are several things that I notice:

* You set `hibernate.dbcp.validationQuery`, should not that be <code>hibernate.<i>c3p0</i>.validationQuery</code>?
* As far as I got it, `hibernate.c3p0.validate` (set to true) and `c3p0.testConnectionOnCheckout` (set to false) mean the same thing. I would try to set both to true.
* In documentations, I find `c3p0.preferredTestQuery` without `;`
* `c3p0.timeout` with 30 seconds is quite short. Perhaps you want to increment that.
* May be the connection was closed by MySQL. The timeout can be configured [as described here](http://stackoverflow.com/a/14726944/1503237).
* As to [this response](http://stackoverflow.com/a/32944423/1503237), _autoReconnect_ is problematic, because it does refresh a connection only _after_ an error occurred. This would mean to wrap all Hibernate statements with an additional catch, like
```
try {
    a = getSomething();
} catch (HibernateException e) {
    a = getSomething();
}
```
I don’t like the last solution.

**Comment by henning-gerhardt** [comment] 2016-06-13 11:40
Thank you Matthias for your advises. Some notes from my testing:
- Error appear independent of local database or remote database server.
- Error appear even with default configuration files of hibernate and c3p0.
- Error appears on first process, not between exporting
- Bigger batches (> 5.000 processes per batch) are more affected by this error then small batches (< 1.000 processes per batch).

For me it looks like a timing issue: production needs to many time to calculate everything and in this time frame the database connection is be closed or not usable any more. It takes over 15 minutes for a 7.500 processes batch from start exporting until first directory is created. A batch with 12.000 processes takes over 30 minutes

A side note: exporting big batches takes a long time: 7 processes per minute is very slow. It takes 17 hours to export 7.500 processes on a local machine (metadata and created export files are on same disc without any additional files like image or ocr files).

**Comment by matthias-ronge** [comment] 2016-06-13 15:22
The problem here is probably that the file groups are lazily initialized. [Here is a branch which forces the initialization of the file groups at the beginning.](https://github.com/matthias-ronge/goobi-production/tree/initialize-filegroups) I hope it will fix the issue. Please test it.

**Comment by henning-gerhardt** [comment] 2016-06-15 14:45
I test your commit but it does not solve the issue but I go a step closer to the real issue. 

I changed MySQL `wait_timeout` and `inactive_timeout` default values from 28800 seconds or 8 hours to 900 seconds or 15 minutes and Hibernate / c3p0 `c3p0.unreturnedConnectionTimeout` value to 800 seconds to decrease idle and open MySQL server connections as we run out of possible database connections. On a normal day we have over 700 parallel idle connections which is a lot and increasing this connection pool is a bad way as this wasted resources could be used by database server in a better way.

If I increased values for `wait_timeout` and `inactive_timeout` to 3600 seconds our biggest batch (12000 processes) could be exported on my local development machine and could hopefully be exported on productive environment too.

**Closed** 2024-03-06 11:24 UTC
Labels: bug, 2.x
