### ISSUE TITLE
Tomcat start with Eclipse on Windows broken, local-config ignored

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#5999] opened 2024-03-08 09:04 UTC
**Describe the bug**
Tomcat no longer starts from Eclipse under Windows. The reason turns out to be that the `kitodo_config.properties` from the `config-local` directory is no longer deployed, but rather the one from `Kitodo/src/main/resources`. Without the local path information, Tomcat will not start, not least because it can no longer find the modules directory.

**To Reproduce**
1. Launch Tomcat [from Eclipse](/kitodo/kitodo-production/wiki/Developer_3.x-Getting-started-Eclipse-Windows)
2. See error

**Expected behavior**
Build must use `kitodo_config.properties` from the `config-local`.

**Release**
Current master (3.7.0-SNAPSHOT)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 123.0.1

**Additional context**
When Tomcat starts and logging was set to `debug` level before, you will find a log entry like:

    Config - Using configuration from file:/<workspace-path>/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/kitodo/WEB-INF/classes/kitodo_config.properties

Previously, this file was a copy of `config-local/kitodo_config.properties`, and now it is a copy of `Kitodo/src/main/resources/kitodo_config.properties`.

**Comment by matthias-ronge** [comment] 2024-03-08 09:05
Testing revealed that the error was introduced with commit https://github.com/kitodo/kitodo-production/commit/8062b8caa66b08aee2d428b03e1f77235a005fe4. Undoing this change fixes it.

**Comment by henning-gerhardt** [comment] 2024-03-08 09:39
@matthias-ronge : You are sure using the development profile? If development profile is not active I can confirm your issue which is correct. With an active development profile the data gets copied. Copying the files from the `config-local` folder is depending on or done by the `properties-maven-plugin` which was not changed in this commit.

**Comment by henning-gerhardt** [comment] 2024-03-08 11:14
The `development` profile is active? If not the default resources are used. Even maybe `all-tests` and / or `selenium` profile interact with the copying of files.

**Comment by matthias-ronge** [comment] 2024-03-11 09:40
Tests don’t execute when running from the command prompt. The reason is the same, the configuration does not fit:

```
[INFO] Running org.kitodo.imagemanagement.ImageManagementIT
[DEBUG] 2024-03-11 10:07:59.898 [main] PropertiesConfiguration - FileName set to kitodo_config.properties
[DEBUG] 2024-03-11 10:07:59.909 [main] ConfigurationUtils - ConfigurationUtils.locate(): base is null, name is kitodo_config.properties
[DEBUG] 2024-03-11 10:07:59.909 [main] DefaultFileSystem - Could not locate file kitodo_config.properties at null: no protocol: kitodo_config.properties
[WARN ] 2024-03-11 10:07:59.929 [main] Config - Loading of kitodo_config.properties failed. Trying to start with empty configuration.
org.apache.commons.configuration.ConfigurationException: Cannot locate configuration source kitodo_config.properties
```

It is not possible to develop quickly in this way.

**Comment by henning-gerhardt** [comment] 2024-03-11 09:54
Only to be sure: the `development` profile is active? 

But even without an active `development` profile the tests and integration tests should run without a locale configuration as they do it on the GitHub actions every time.

How did you can develop in the past as the commit was merged into master in December 2023? Maybe there are other changes since December 2023 on your system which now results in this errors?

Don't get me wrong as I would help you but without an Windows based system I can't and I can only ask you different things.

**Closed** 2024-05-03 11:08 UTC
Labels: bug, blocking
