### ISSUE TITLE
Sorting of process list by ID does not work

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3417] opened 2020-04-08 16:06 UTC
The sorting of the process list by ID does not work. It is not clear by which criteria the processes are sorted

**Comment by matthias-ronge** [comment] 2020-04-14 09:17
Possible duplicate of #3299

**Comment by andre-hohmann** [comment] 2020-04-14 09:23
The sorting does not work generally - not only the initial sorting. There are some blocks of sorted processes, so at the first glance, it looks fine.  But if you scroll the process list, you will find several blocks. 
It doesn't matter if the order is ascendig or descending, ...

**Closed** 2020-05-15 12:06 UTC
Labels: 3.x, blocking, bug
