### ISSUE TITLE
I cannot use a ruleset title, if it already exists in another client (Mandant)

### ISSUE THREAD

**Issue by daropoi** [kitodo/kitodo-production#4387] opened 2021-05-06 10:22 UTC
I have tested a group of project, template, workflow, docket and ruleset in my test-client. 

I now want to take over / copy this structure to my production-client. This does not work. When adding a new ruleset, I get the error message: "The ruleset with the same title exists already."
But it does not exist in **this** client.

I should be able to have ruleset (project, template, workflow, docket) with same title in another client.

**Comment by solth** [comment] 2021-05-15 06:44
Duplicate of #3726

**Comment by matthias-ronge** [comment] 2021-06-02 07:02
Closed as duplicate. @daropoi please subscribe to #3726 instead

**Closed by matthias-ronge** 2021-06-02 07:02 UTC
Labels: 3.x, improvement
